### ISSUE TITLE
Drools tests are failing

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#15] opened 2017-03-28 23:35 UTC
These tests are failing
 - DroolsActivity
 - DroolsDecisionTable
 - DroolsMultisheetDecisionTable

With errors like:
```[(s)20170401.09:49:13.123 ~267] Error parsing knowledge base from rules for DROOLS: drools-orderRoutingDrool.drl v1
Rule Compilation error : [Rule name='Western Region Rule']
	com/centurylink/mdw/tests/Rule_Western_Region_Rule1875196454.java (2:43) : Only a type can be imported. java.util.Date resolves to a package
	com/centurylink/mdw/tests/Rule_Western_Region_Rule1875196454.java (2:86) : Only a type can be imported. com.centurylink.mdw.workflow.activity.rules.DroolsActivity resolves to a package
	com/centurylink/mdw/tests/Rule_Western_Region_Rule1875196454.java (6:328) : org.drools.spi.KnowledgeHelper cannot be resolved to a type
	com/centurylink/mdw/tests/Rule_Western_Region_Rule1875196454.java (6:370) : com.centurylink.mdw.workflow.activity.rules.DroolsActivity cannot be resolved to a type
	com/centurylink/mdw/tests/Rule_Western_Region_Rule1875196454.java (6:470) : org.drools.runtime.rule.RuleContext cannot be resolved to a type
```

**Comment by donaldoakes** [comment] 2017-04-07 19:50
All other tests are routinely passing in mdw6.

**Comment by donaldoakes** [comment] 2017-04-17 21:35
I've moved our drools dependencies to asset package com.centurylink.mdw.drools and upgraded to Drools 6.5.0.Final.  Now the focus of this issue is to make sure the code in this package functions correctly with Drools 6.

**Comment by vimala-nagarja-CTL** [comment] 2017-04-20 07:02
1.	Moved most of the imports to KIA packages to overcome ClassCastException. ( I have checked in these java files.)
2.	KnowledgeBuilderFactory from KIE package, depends on classes from jbpm-flow-builder.jar. So added this jar under mdw-workflow/assets/com.centurylink.mdw.drools package.
3.	When the Drools activitity is run, I am getting below NoClassDefFoundError.  The root cause is : java.lang.ClassNotFoundException: org.drools.compiler.ProcessBuilderFactoryService.
The latest ProcessBuilderFactoryService class is present in org.drools.compiler.compiler.ProcessBuilderFactoryService package in drools-compiler-6.5.0.Final.jar. (Looks like this
Is a bug in ServiceRegistryImpl class. 



java.lang.NoClassDefFoundError: org/drools/compiler/ProcessBuilderFactoryService
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.centurylink.mdw.cloud.CloudClassLoader.findClass(CloudClassLoader.java:153)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.centurylink.mdw.cloud.CloudClassLoader.loadClass(CloudClassLoader.java:330)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.kie.internal.utils.ServiceRegistryImpl$ReflectionInstantiator.newInstance(ServiceRegistryImpl.java:270)
	at org.kie.internal.utils.ServiceRegistryImpl$ReflectionInstantiator.call(ServiceRegistryImpl.java:265)
	at org.kie.internal.utils.ServiceRegistryImpl.get(ServiceRegistryImpl.java:167)
	at org.drools.compiler.compiler.ProcessBuilderFactory.loadProvider(ProcessBuilderFactory.java:54)
	at org.drools.compiler.compiler.ProcessBuilderFactory.getProcessBuilderFactoryService(ProcessBuilderFactory.java:40)
	at org.drools.compiler.compiler.ProcessBuilderFactory.newProcessBuilder(ProcessBuilderFactory.java:30)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.createProcessBuilder(KnowledgeBuilderImpl.java:307)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.<init>(KnowledgeBuilderImpl.java:301)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.<init>(KnowledgeBuilderImpl.java:245)
	at org.drools.compiler.builder.impl.KnowledgeBuilderFactoryServiceImpl.newKnowledgeBuilder(KnowledgeBuilderFactoryServiceImpl.java:58)
	at org.kie.internal.builder.KnowledgeBuilderFactory.newKnowledgeBuilder(KnowledgeBuilderFactory.java:55)
	at com.centurylink.mdw.drools.DroolsKnowledgeBaseCache.loadKnowledgeBaseAsset(DroolsKnowledgeBaseCache.java:201)
	at com.centurylink.mdw.drools.DroolsKnowledgeBaseCache.getKnowledgeBaseAsset(DroolsKnowledgeBaseCache.java:126)
	at com.centurylink.mdw.drools.DroolsActivity.getKnowledgeBase(DroolsActivity.java:119)
	at com.centurylink.mdw.drools.DroolsActivity.getKnowledgeBase(DroolsActivity.java:106)
	at com.centurylink.mdw.drools.DroolsActivity.execute(DroolsActivity.java:69)
	at com.centurylink.mdw.workflow.activity.DefaultActivityImpl.execute(DefaultActivityImpl.java:41)
	at com.centurylink.mdw.services.process.BaseActivity.execute(BaseActivity.java:221)
	at com.centurylink.mdw.services.process.BaseActivity.executeTimed(BaseActivity.java:231)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:379)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:612)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvents(ProcessEngineDriver.java:578)
	at com.centurylink.mdw.services.process.InternalEventDriver.run(InternalEventDriver.java:37)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$Work.run(CommonThreadPool.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$ManagedThread.run(CommonThreadPool.java:232)
Caused by: java.lang.ClassNotFoundException: org.drools.compiler.ProcessBuilderFactoryService
	at com.centurylink.mdw.cloud.CloudClassLoader.findClass(CloudClassLoader.java:140)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.centurylink.mdw.cloud.CloudClassLoader.loadClass(CloudClassLoader.java:330)
	... 37 more

**Closed** 2017-04-20 23:34 UTC
Labels: Defect
