### ISSUE TITLE
Archived process request mappings cause conflicts

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#433] opened 2018-05-24 19:48 UTC
Archived processes with the same path as the current proc cause conflicts (noted in the startup log for the server).  Instead we should ignore archived processes when mapping request paths/methods to workflows.

**Comment by vimala-nagarja-CTL** [comment] 2018-05-28 11:50
Hi Don,
  I have many archived packages in my local workspace and tried various things but not able to reproduce this issue.  Can you please give one example?

**Comment by vimala-nagarja-CTL** [comment] 2018-05-31 09:27
In LoaderPersisterVcs.java,
 public List<PackageDir> getPackageDirs() throws DataAccessException {
        return getPackageDirs(false); // setting this to false will not fetch archived package directories.
    }
Since it is a very small change, I directly committed to master branch.

**Closed** 2018-06-04 04:39 UTC
Labels: defect
