### ISSUE TITLE
Remove old-style Action and Resource services

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#361] opened 2018-03-23 15:56 UTC
Replace all services under these packages (at least those that are still used by Designer and have no current equivalent):
 - com.centurylink.mdw.service.action
 - com.centurylink.mdw.service.resource

Also remove compatibility code in ServiceRequestHandler.java.

Related Designer issue:
https://github.com/CenturyLinkCloud/mdw-designer/issues/60

**Comment by jbrojdeCTL** [comment] 2018-03-26 22:32
Naveena, I'm going thru all these services and documenting what would need to be changed in Designer to retrieve the same information for server >= 6.1.

- DocumentValue:   For this, Designer needs to change path to DocumentValues/{documentId}

- ExternalMessageInstance:  Designer would change to call Requests rest service.  If you have an eventInstId, then Designer would call Requests/{eventInstId}.   If eventInstId is null, Designer would call Requests?ownerId=activityInstId&type=outboundRequests.  Designer would then have to build the expected JSONObject to feed into ExternalMessageVO contructor. 

- AuditLog:  Designer should not be calling this service at all.  Responsibility/decision to auditLog for a particular action should rest with service, not designer.  Designer should remove all calls to AudiLog.  

-  RefreshCache:  Designer should call WorkflowCache service instead of ActionRequestDocument in method RestfulServer.refreshCache().

- UnitTests:  Designer should call AutomatedTests service instead of using ActionRequestDocument in method GroovyTestCaseRun.run()

Rest of them....to be continued....

**Comment by naveena-bellamkonda** [comment] 2018-03-29 05:07
Hi Jack,
The below are being used by designer as direct server calls with authentication.
a) <_mdw_document_content>
b) <_mdw_refresh>
c) <_mdw_property>
d) <_mdw_peer_server_list>

<_mdw_update_variable> used to be called depending on the isUpdateable value (true/false) of the DocumentValue service response. I think DocumentValues service for 6.1 is not returning isUpdateable. Even 55 code is just setting this value to the json object and i dont see the same is being returned. So I think <_mdw_update_variable> can be removed for 6.

**Comment by jbrojdeCTL** [comment] 2018-03-29 22:03
Naveena, I have now checked in the code changes that will enforce Authentication is needed (if not in dev mode) for external event handlers, plus the special handler for `<_mdw_*>` messages.   This would include the ActionRequest messages where Action has Name=RegressionTest attribute.  Up until now, the compatibility stuff was still there and no authentication/authorization took place for these.

**Closed** 2018-04-05 22:39 UTC
Labels: enhancement
