### ISSUE TITLE
Allow missing db configuration for VCS Assets projects

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#54] opened 2017-03-30 05:50 UTC
In com.centurylink.mdw.plugin.xml, the element should be removed for mdw6 vcs assets. We should go exclusively through the server. Anyway, at this time db connection is only a fallback for user permissions so that the server does not have to be running. But we should make a running server a prerequisite for any non-local operations anyway.

**Comment by donaldoakes** [comment] 2017-04-07 17:35
Duplicate of #4.

**Closed by donaldoakes** 2017-04-07 17:35 UTC
Labels: Enhancement
